# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Robalar
tagline:          'A blog...of some description'
description:      'When I stumble across something interesing and worth sharing this is where it shall live.'
url:              http://robalar.github.io
baseurl:          /

author:
  name:           'Robert Hales'
  url:            https://twitter.com/robalardev

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/robalar
