# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Robalar
tagline:          'A blog...of some description'
description:      ''
url:              http://robalar.github.io
baseurl:          /

author:
  name:           'Robert Hales'
  url:            https://twitter.com/robalardev

paginate:         5
